---
- name: create groups by distribution
  hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- hosts: Debian:Ubuntu
  gather_facts: False
  roles:
    - ubuntu
    - common

- hosts: CentOS:RedHat
  gather_facts: False
  roles:
    - redhat
    - common
