---
- name: create groups by distribution
  hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- hosts: Debian:Ubuntu
  gather_facts: False
  roles:
    - base/ubuntu
    - base/common

- hosts: CentOS:RedHat
  gather_facts: False
  roles:
    - base/redhat
    - base/common

- hosts: chat.rax.mbs3.org
  gather_facts: False
  roles:
    - chat
