---
- user: name=martin comment="Martin Smith" shell="/bin/bash"

- name: Set up authorized_keys for the martin user
  authorized_key: user=martin
                  key="{{ item }}"
  with_file:
    - id_rsa_cloudhosts.pub
